# Generated by Django 3.1.2 on 2020-10-21 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_genres', models.CharField(max_length=200, verbose_name='Жанр')),
                ('book_name', models.CharField(max_length=200, verbose_name='Название книги')),
                ('book_author', models.CharField(max_length=200, verbose_name='Автор')),
                ('book_publisher', models.CharField(max_length=200, verbose_name='Издательство')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=55, verbose_name='Имя пользователя')),
                ('comment_text', models.CharField(max_length=300, verbose_name='текст комментари')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_tabl.book')),
            ],
        ),
    ]
