# Generated by Django 3.1.2 on 2020-10-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_tabl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='текст комментари'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Имя пользователя'),
        ),
    ]
