# Generated by Django 3.1.2 on 2020-10-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_tabl', '0002_auto_20201021_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена в BYN'),
        ),
        migrations.AddField(
            model_name='book',
            name='books_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_code',
            field=models.CharField(default='', max_length=20, verbose_name='ISBN'),
        ),
    ]
