# Generated by Django 3.1.2 on 2020-11-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_tabl', '0004_auto_20201102_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_genres',
            field=models.CharField(default='', max_length=200, verbose_name='Жанр'),
        ),
    ]
