# Generated by Django 3.1.2 on 2020-11-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_tabl', '0005_auto_20201102_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(default='', max_length=200, verbose_name='Название книги'),
        ),
    ]
